name: Deploy

on: 
  push:
    branches:
    - main 

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'AKIARHK4NUKJH7SGMOR3'
          aws-secret-access-key: '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'
          aws-region: ap-south-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy 
        run: |
          cd ./../.
          zip -r deploy.zip ./*
          aws lambda update-function-code --function-name=arn:aws:lambda:ap-south-1:084482564754:function:lambda-app-dev-app --zip-file=fileb://deploy.zip
